### ISSUE TITLE
Add new "full_status_check" option to aktualizr-lite docs

### ISSUE THREAD

**Issue by doanac** [foundriesio/docs#105]
aktualizr-lite just added a new flag for controlling a feature:

 https://github.com/foundriesio/aktualizr-lite/pull/27/files

We should add this to https://github.com/foundriesio/docs/blob/master/source/reference/aktualizr-lite.rst. Probably need a section for interesting config options.

**Comment by doanac** [comment]
@mike-sul - wanna take a shot?

**Comment by mike-sul** [comment]
@doanac OK, what mechanisms of aklite configuration should we mention in this doc, just fioct or direct config file configuration is also allowed?

**Comment by doanac** [comment]
i think we list the most interesting ones like the check-in interval, disabling docker prune, the label that docker prune ignores, compose_bin, compose_dir. there might be more, that's just off the top of my head

**Comment by mike-sul** [comment]
I meant a bit another aspect - the way(s) to change the config params. Should I write "you can change params by editing sota.toml directly on a device"

**Comment by doanac** [comment]
ah. so maybe there's two parts. 1) just explaining the "knobs" and 2) explaining strategies for configuring them? I think most of this is for when someone is trying to debug, so direct editing is probably fine.
