### ISSUE TITLE
Update "Additional Linux microPlatform Targets" section

### ISSUE THREAD

**Issue by MatthewCroughan** [foundriesio/docs#107]
https://docs.foundries.io/latest/reference/linux-targets.html?highlight=machines

At time of writing, this section refers to the `setup-environment` script. This specific workflow is now with editing the `machine:` key value in `factory-config.yml`. This needs to be updated to reflect this.

**Comment by mike-scott** [comment]
@MatthewCroughan ok to close?
https://github.com/foundriesio/docs/commit/3198b27930e6aa246331fdc61c28c22e03abc772

**Comment by MatthewCroughan** [comment]
Yup @mike-scott
