### ISSUE TITLE
document the use of "[skip ci]" tag in the last commit of a push

### ISSUE THREAD

**Issue by mike-scott** [foundriesio/docs#129]
This stops the builders from generating a new build for this push

**Comment by doanac** [comment]
Looks like we missed this in the refactor:

 https://github.com/foundriesio/docs/blob/mp-73/source/customer-factory/source-code.rst#triggering-builds

Not sure how/where we want to put that now. I think that "triggering builds" section is good info though.

**Comment by mike-scott** [comment]
@MatthewCroughan This one is probably an easy fix
