### ISSUE TITLE
Updating the Linux microPlatform Core: git reset will need a git push -f (force)

### ISSUE THREAD

**Issue by mike-scott** [foundriesio/docs#135]
Where:
https://docs.foundries.io/latest/reference-manual/linux/linux-update.html?#updating-the-linux-microplatform-core

What:
If the subscriber wants to "undo" a merge of LmP we recommend:
`git reset --hard HEAD~1`

However, that means we will need to "force" the next command:
`git push -f`

**Comment by ricardosalveti** [comment]
We might need to add a bit more info or even a warning here as a git push -f might result in broken factories if the user is not so familiar with git.
