### ISSUE TITLE
Extend build lmp from source to refer to the lmp-manifest repo used by a factory

### ISSUE THREAD

**Issue by ricardosalveti** [foundriesio/docs#159]
https://docs.foundries.io/latest/reference-manual/linux/linux-building.html covers the build from source process using the public repos (public lmp) only.

We should extend that page covering how to build lmp from source based on a certain factory/branch, and explain the difference between a factory build and our public build.

**Comment by kprosise** [comment]
Moving issue to Jira. It appears this has been partially addressed, but the difference isn't really detailed.
