### ISSUE TITLE
Switch to MkDocs

### ISSUE THREAD

**Issue by MatthewCroughan** [foundriesio/docs#178]
# Things we can't do without great difficulty in Sphinx:

- Insert device related info on a page (with conditionals) https://github.com/foundriesio/docs/issues/164#issuecomment-769193590
 - E.g: If this page has the "imx8mm" tag, then insert a link in a note at the bottom
    of page

- Collaborate easily as a team (All written in markdown)
  - Well thought out and separated functionality for
    - Writers (Us)
    - Designers (Milo)
    - Contributors (Anyone)
  This is demonstrated [here](https://github.com/foundriesio/docs/issues/164#issuecomment-769193590)

# Who uses it?

* [GlusterFS](https://docs.gluster.org/en/latest/)
* [Traefik](https://doc.traefik.io/traefik/)
* [Flox](https://beta.floxdev.com/docs/why-flox/versus_docker/)

## Benefits
- Most of the Sphinx plugins we are using are native functionality in MkDocs.
- No cruft. Sphinx was developed to document Python code, thus has a lot of
  superfluous functionality that often gets in the way of the way we want to
  document normal things. This is primarily why RST is used.
  - Cares about indendation (Makes development slower and expression of spaces and newlines harder due to the amount of technicalities with indentation)
  - Too strict (Makes CI really hard due to false positive errors that cannot easily be ignored or turned off)

- Better SEO (via tags and author details, etc.) https://github.com/foundriesio/docs/issues/137

##  Notes

- Small but determined community, available in the #mkdocs IRC
  - Usually pretty responsive
  - Issues are fixed in days

- Written in Python, just like Sphinx.

- Provides Jinja templating with conditionals as native functionality
  - https://github.com/foundriesio/docs/issues/164#issuecomment-769193590

- Is just plain better than Sphinx for what we're doing

### Yocto developers

Wrote their own incomplete pre-processor just to replace ampersand `&variable`'s

These variables are global, meaning we still cannot make smart pages and
templates that fill out depending on local variables like the architecture the
file says it represents - using markdown tags/labels for example: (%arm64,
%riscv64, %etc).

- Nicolas Dechesne had to write these pre-processors in Python
    [Commit1](https://git.yoctoproject.org/cgit/cgit.cgi/yocto-docs/commit/documentation/sphinx/yocto-vars.py?id=dc5f53fae8fdfdda04285869dd1419107b920bfe)
    [Commit2](https://git.yoctoproject.org/cgit/cgit.cgi/yocto-docs/commit/documentation/sphinx/yocto-vars.py?id=59537c7fa49e3ea6918f45b3201ad16d56988b9b)

**Comment by MatthewCroughan** [comment]
From time to time, we struggle with redirects. Redirects are made manageable in MkDocs without modifying the webserver configuration via this plugin https://pypi.org/project/mkdocs-redirects/

**Comment by kprosise** [comment]
Reasoning copied to confluence as arguments in support of MkDocs.Closing issue.
