### ISSUE TITLE
Document update needed in Updating the Linux microPlatform Core

### ISSUE THREAD

**Issue by gcgrey** [foundriesio/docs#25]
The default git version in macOS Mojave is 2.21
The update-factory-manifest script uses:
git branch --show-current
which is not supported necessitating updating git to the latest version. 

Note - not tested on macOS Catalina

**Comment by MatthewCroughan** [comment]
Seems not to be an issue on Catalina, as tested by me on a fresh VM which is running it.

```
macvm:docs matthew$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76
macvm:docs matthew$ git branch --show-current
master
```
