### ISSUE TITLE
Managing Your Device Gateway: Setting up your PKI: make it more clear that the fioctl command creates the artifacts

### ISSUE THREAD

**Issue by mike-scott** [foundriesio/docs#356]
Regarding:
https://docs.foundries.io/latest/reference-manual/security/device-gateway.html#setting-up-your-pki

There is some confusion that the `fioctl keys ca create /absolute/path/to/certs/` command creates EVERYTHING you need to start provisioning device-based certificates.  Not exactly sure how that can be made more clear.

The `Terminology` section is great, but it has the side-effect of "burying" the `fioctl` command that you need to run first.

**Comment by kprosise** [comment]
Noted! Mind if I move this over to Jira?

**Comment by mike-scott** [comment]
Yes, please do :)

**Comment by kprosise** [comment]
[Done](https://foundriesio.atlassian.net/browse/FFTK-1469)
