### ISSUE TITLE
Please clarify LICENSE

### ISSUE THREAD

**Issue by gmacario** [foundriesio/docs#369]
I could not find any `LICENSE` file in this repository.

Under which license is this repository licensed?

Reference: <https://choosealicense.com/>

**Comment by kprosise** [comment]
@gmacario I'll take a look, and will add the LICENSE file.

**Comment by gmacario** [comment]
> @gmacario I'll take a look, and will add the LICENSE file.

Thanks! It would be great if the LICENSE is compatible with - for instance - https://github.com/arduino/docs-content/blob/main/LICENSE.md

**Comment by kprosise** [comment]
@gmacario Yep, that was exactly the license that I am going to purpose, I should have this set soon as I get the okay to do so.

**Comment by kprosise** [comment]
@gmacario added and merged!
