### ISSUE TITLE
Explain how users come into contact with TUF keys 

### ISSUE THREAD

**Issue by dagriego** [foundriesio/docs#67]
The documentation states that user should generate a token after factory is created, but what actually happened is that I received an email that contained a one-time download link to get the token needed to access the factory.

[https://docs.foundries.io/latest/customer-factory/getting-started.html#generate-an-access-token](url)

**Comment by doanac** [comment]
The email is referring to your offline TUF keys. An API token is a different thing needed to access things like source.foundries.io from git.

**Comment by MatthewCroughan** [comment]
That's the same as #64. Does the .netrc file get used for anything other than `git` and `fioctl`? This is the only thing preventing me from explaining it fully, as I assume it may get used for lots of things in the future. What is its scope? @doanac

**Comment by doanac** [comment]
.netrc isn't used by fioctl. fioctl now uses a "login" method that uses standard oauth tokens. An API token is used for:

 * Accessing our apis (api.foundries.io)
 * Accessing git (source.foundries.io)
 * Accessing docker (hub.foundries.io)

netrc is our recommended approach for making source.foundries.io less cumbersome.

**Comment by dagriego** [comment]
> The email is referring to your offline TUF keys. An API token is a different thing needed to access things like source.foundries.io from git.

I guess what confused me was in the tgz file was config.json file and I was able to use client_id and client_secret from there to access the souce.foundries.io by putting these values in my .netrc file!

**Comment by doanac** [comment]
> I guess what confused me was in the tgz file was config.json file and I was able to use client_id and client_secret from there to access the souce.foundries.io by putting these values in my .netrc file!

that's very clever. in the near future our "scoped tokens" will help prevent this kind of (ab)use case.

**Comment by MatthewCroughan** [comment]
[Currently the docs for TUF keys are quite good already](https://docs.foundries.io/latest/reference/offline-keys.html?highlight=tuf%20key), it would be a good idea to outline that the user gets them when a factory is made by an email and put it in a relevant section like getting-started. This is a small edit, this issue will be closed when done.

**Comment by doanac** [comment]
@MatthewCroughan - this is probably something we should raise as another bug, but ... The current docs explain how to do what we call a "root key rotation". We'll need to eventually explain a procedure for updating a factory's "targets" signing key as well.

**Comment by MatthewCroughan** [comment]
Solved by 730c98d in #82
