### ISSUE TITLE
Configuring Devices using fioctl not working as in example.  'Error required flag "factory" not set'

### ISSUE THREAD

**Issue by dagriego** [foundriesio/docs#69]
In the [example](https://docs.foundries.io/latest/customer-factory/configuring.html#fleet-wide-configuration):
# View log of config changes (similar to "git log")
fioctl config log
 I get the error:
Error required flag "factory" not set

To get around this I needed to add the --factory flag
fioctl --factory <factory name> config log

**Comment by doanac** [comment]
I'm not sure how we could mention this, but if you only belong to a single factory (which a normal user likely will) and you use `fioctl login`, then this commit should set a default factory for you:

 https://github.com/foundriesio/fioctl/commit/df095f8da91f394267a4a821d879deba78013e51

I'm guessing we should just be explicit with "-f" in docs and let users discover this over time?

**Comment by MatthewCroughan** [comment]
I believe this was fixed by https://github.com/foundriesio/fioctl/pull/53. This was my experience too, as foundriesio/fioctl@df095f8 would not be utilized due to the bug. If I have misunderstood this feel free to reopen.
