### ISSUE TITLE
BUILDDIR needs to be set be inside the lmp directory for local build

### ISSUE THREAD

**Issue by dagriego** [foundriesio/docs#70]
When setting up for a local build using the instructions here: https://docs.foundries.io/latest/reference/linux-building.html#set-up-work-environment

The example states:
MACHINE=raspberrypi3-64 source setup-environment [BUILDDIR]

but BUILDDIR (if used) must be in the lmp directory or your build will fail

Reproduce:

MACHINE=raspberrypi3-64 source setup-environment ~/raspberrypi3-64

dgriego@foundries-x86-build:~/lmp/home/dgriego/raspberrypi3-64$ bitbake -s
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/dgriego/lmp/home/dgriego/raspberrypi3-64/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 17433 at 2020-07-08 16:18:20.983557 ---
ERROR: The following layer directories do not exist:
ERROR:    /home/dgriego/lmp/home/dgriego/raspberrypi3-64/conf/../../layers/meta-lmp/meta-lmp-base
ERROR:    /home/dgriego/lmp/home/dgriego/raspberrypi3-64/conf/../../layers/meta-openembedded/meta-oe
ERROR:    /home/dgriego/lmp/home/dgriego/raspberrypi3-64/conf/../../layers/meta-openembedded/meta-networking
{snip}

**Comment by kprosise** [comment]
Closing issue, [relocated to Jira](https://foundriesio.atlassian.net/browse/FFTK-998)
