### ISSUE TITLE
Explain signing key rotation of a factory's targets

### ISSUE THREAD

**Issue by MatthewCroughan** [foundriesio/docs#76]
@MatthewCroughan - this is probably something we should raise as another bug, but ... The current docs explain how to do what we call a "root key rotation". We'll need to eventually explain a procedure for updating a factory's "targets" signing key as well.

_Originally posted by @doanac in https://github.com/foundriesio/docs/issues/67#issuecomment-661979870_

**Comment by kprosise** [comment]
Closing issue, as there has already been a fair amount of change around this.
