### ISSUE TITLE
Use fioctl gen-rst in docs

### ISSUE THREAD

**Issue by MatthewCroughan** [foundriesio/docs#90]
It should be considered how to best integrate the automated documentation from https://github.com/foundriesio/fioctl/pull/55. I like the idea of having a `man-pages` section/folder, much like OpenZFS has recently started to do with their sphinx docs and just placing it all in there. 

https://openzfs.github.io/openzfs-docs/man/index.html

Since I am currently working on https://github.com/foundriesio/docs/pull/88, it would be best to merge this first, then make a separate PR which integrates this CI and solves this issue, so we can take the content that I have produced and put in its correct location.

**Comment by mike-scott** [comment]
@MatthewCroughan ok to close?

**Comment by MatthewCroughan** [comment]
Yup, as part of #115
