### ISSUE TITLE
Redirect app.foundries.io/docs -> docs.foundries.io

### ISSUE THREAD

**Issue by MatthewCroughan** [foundriesio/docs#94]
Upon noting #93, I noticed that app.foundries.io/docs resolves and does not redirect to docs.foundries.io. @MiloCasagrande has noted that we should redirect to docs.foundries.io in the future. I am noting down this issue as not to forget and to fill out more details that are important, since this may be a reference for future issues that may occur due to the change. (hopefully not)

**Comment by MiloCasagrande** [comment]
Should be redirected to docs.foundries.io now.
In case I missed something somewhere, let me know
