### ISSUE TITLE
refactor-improvements-1

### ISSUE THREAD

**Issue by doanac** [foundriesio/docs#98]
In the [reference manual](https://ci.foundries.io/projects/fio-docs/builds/558/docs/artifacts/html/reference-manual/index.html) we have `fioctl` in the OTA section. I think this belongs in the top "Foundries Factory" section.

>  Upon Factory creation you will be sent an email containing your Offline FoundriesFactory TUF Keys. Read this documentation for information on key rotation.

That's good stuff. Given that its just a "note". I think the more important task to stress is storing this file securely. So maybe it should be something like:
  _Upon Factory creation you will be sent an email containing your Offline FoundriesFactory TUF Keys. Please keep this file stored securely._

> The Linux microPlatform supports a wide range of platforms out of the box. We even provide QEMU images for ARM and RISC-V architectures.

I'm terrible with writing but I think we've generally avoided using 1st person voices. So maybe this could be:
 _The Linux microPlatform supports a wide range of platforms out of the box even including QEMU images for ARM and RISC-V architectures._

I think "git" needs to be "Git" based on the limited googling I've done: https://ci.foundries.io/projects/fio-docs/builds/558/docs/artifacts/html/getting-started/git-config/index.html

**Comment by MatthewCroughan** [comment]
> In the reference manual we have fioctl in the OTA section. I think this belongs in the top "Foundries Factory" section.

The docs on device tags and config management are also in there, so should other things move along with it? Maybe most of it should move to `factory/`? Any thoughts @EmbeddedAndroid ?

> That's good stuff. Given that its just a "note". I think the more important task to stress is storing this file securely. So maybe it should be something like:
Upon Factory creation you will be sent an email containing your Offline FoundriesFactory TUF Keys. Please keep this file stored securely.

34a4377ec19e5041dd30d6299a6dc240125a9b3a

> I'm terrible with writing but I think we've generally avoided using 1st person voices. So maybe this could be:
The Linux microPlatform supports a wide range of platforms out of the box even including QEMU images for ARM and RISC-V architectures.

7ecb18285ca65ad99b3ba12d52e725f3a1f0bd85

> I think "git" needs to be "Git" based on the limited googling I've done: https://ci.foundries.io/projects/fio-docs/builds/558/docs/artifacts/html/getting-started/git-config/index.html

b832d2ccc4be0ef57e2552715ffa3ed172b742a7
